import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    'dashboard': 'Dashboard',
    'deploy': 'Deploy Model',
    'deployments': 'Deployments',
    'releases': 'Releases',
    'traffic': 'Traffic Management',
    'costs': 'Costs',
    'quotas': 'Quotas',
    'audit': 'Audit',
    'access': 'Access Management',
    'economics': 'Economics Settings',
    'economicsSub': 'Configure inference tariffs and electricity price metrics.',
    'tariffCatalog': 'Tariff Catalog',
    'energyEconomics': 'Energy Economics',
    'pricingLogic': 'Pricing Logic',
    'addUser': 'Add User',
    'newTeam': 'New Team',
    'createRole': 'Create Role',
    'platformRole': 'Platform Role',
    'team': 'Team',
    'allowedModels': 'Allowed Models',
    'members': 'Members',
    'teamRole': 'Team Role',
    'roleName': 'Role Name',
    'roleDescription': 'Role Description',
    'permissionsMatrix': 'Permissions Matrix',
    'currentActivePermissions': 'Active Permissions Summary',
    'description': 'Description',
    'selectModels': 'Select Models',
    'autoCalculateCost': 'Auto-calculate cost',
    'prometheusData': 'Prometheus Data',
    'wattsPerReplica': 'Watts per Replica',
    'baseKwhPrice': 'Base electricity cost (₽/kWh)',
    'currentCluster': 'Current Cluster',
    'allClusters': 'All clusters',
    'modelName': 'Model Name',
    'replicas': 'Replicas',
    'status': 'Status',
    'product': 'Product',
    'createdAt': 'Created',
    'actions': 'Actions',
    'active': 'Active',
    'running': 'Running',
    'pending': 'Pending',
    'failed': 'Failed',
    'succeeded': 'Succeeded',
    'rolledBack': 'Rolled Back',
    'multiCluster': 'Multi-cluster',
    'deployToMultiple': 'Deploy to multiple regions',
    'preDeployValidation': 'Pre-deploy Validation',
    'startDeploy': 'Start Deployment',
    'startRelease': 'Start Release',
    'releasesSub': 'Track rollout status, SLOs, and perform multi-cluster migrations.',
    'route': 'Route',
    'source': 'Source',
    'target': 'Target',
    'strategy': 'Strategy',
    'metrics': 'Metrics',
    'timeline': 'Timeline',
    'events': 'Events',
    'pause': 'Pause',
    'resume': 'Resume',
    'rollback': 'Rollback',
    'skipTo100': 'Skip to 100%',
    'throughput': 'Throughput',
    'latency': 'Latency',
    'errorRate': 'Error Rate',
    'successRate': 'Success Rate',
    'rolling': 'Rolling',
    'paused': 'Paused',
    'totalCosts': 'Total Costs',
    'inferenceCost': 'Inference Cost',
    'electricityCost': 'Electricity Cost',
    'totalTokens': 'Total Tokens',
    'energyConsumption': 'Energy Consumption',
    'energyConsumed': 'Consumed',
    'costsHistory': 'Cost History',
    'ratesManagement': 'Rates Management',
    'electricityPrice': 'Electricity Price (per kWh)',
    'inputRate': 'Input (1M tokens)',
    'outputRate': 'Output (1M tokens)',
    'groupByModel': 'Group by Model',
    'groupByTeam': 'Group by Team',
    'groupByUser': 'Group by User',
    'groupByCluster': 'Group by Cluster',
    'groupByDeployment': 'Group by Deployment',
    'inference': 'Inference',
    'electricity': 'Electricity',
    'combined': 'Combined',
    'stacked': 'Stacked',
    'dynamics': 'Dynamics vs past period',
    'activeQuotas': 'Active Quotas',
    'warningAlerts': 'Warning Alerts',
    'quotasManagement': 'Quotas Management',
    'quotasSub': 'Manage token and cost limits across the platform.',
    'newQuota': 'New Quota',
    'subject': 'Subject',
    'subjectType': 'Subject Type',
    'allModels': 'All Models',
    'limit': 'Limit',
    'unit': 'Unit',
    'tokens': 'Tokens',
    'requests': 'Requests',
    'period': 'Period',
    'hour': 'Hour',
    'day': 'Day',
    'month': 'Month',
    'actionOnExceed': 'Action when Exceeded',
    'block': 'Block',
    'throttle': 'Throttle',
    'warn': 'Warn Only',
    'priority': 'Priority',
    'create': 'Create',
    'cancel': 'Cancel',
    'teamProject': 'Team / Project',
    'usageCapacity': 'Usage vs Capacity',
    'edit': 'Edit',
    'healthy': 'Healthy',
    'warning': 'Warning',
    'overLimit': 'Over Limit',
    'uptime': 'Uptime',
    'costLast24h': 'Cost (Last 24h)',
    'metricsOverview': 'System Metrics',
    'metricsDashboard': 'Metrics Dashboard',
    'metricsSub': 'Key performance indicators and system health overview.',
    'accessControl': 'Access Control',
    'accessSub': 'Manage users, teams and permissions for the platform. Access is defined by team membership.',
    'users': 'Users',
    'teams': 'Teams',
    'rolesPermissions': 'Roles & Permissions',
    'manageMembers': 'Manage Members',
    'userPanel': 'User Details',
    'teamPanel': 'Team Details',
    'saveChanges': 'Save Changes',
    'adminSection': 'Admin',
    'memberships': 'Team Memberships',
    'addMembership': 'Add to Team',
    'name': 'Name',
    'Email': 'Email',
    'teamName': 'Team Name',
    'infrastructure': 'Infrastructure',
    'clusters': 'Infrastructure',
    'nodes': 'Nodes',
    'heartbeat': 'Last Heartbeat',
    'allocatable': 'Allocatable',
    'used': 'Used',
    'deployable': 'Deployable',
    'deployHere': 'Deploy Here',
    'gpuUtilization': 'GPU Utilization',
    'ramUtilization': 'RAM Utilization',
    'cpuUtilization': 'CPU Utilization',
    'ready': 'Ready',
    'notReady': 'Not Ready',
    'degraded': 'Degraded',
    'unreachable': 'Unreachable',
    'online': 'Online',
    'technicalTokens': 'Technical Tokens',
    'newTechnicalToken': 'New Technical Token',
    'apiTokens': 'Technical Tokens',
    'deploymentConfig': 'Deployment Config',
    'avgCostPerToken': 'Avg Cost / Token',
    'tokenName': 'Token Name',
    'enterTokenName': 'Enter token name',
    'overallClusterProgress': 'Overall Cluster Progress',
    'podsDeploymentStatus': 'Individual Replica Pod Details',
  },
  ru: {
    'dashboard': 'Дашборд',
    'deploy': 'Развернуть модель',
    'deployments': 'Развертывания',
    'releases': 'Релизы',
    'traffic': 'Управление трафиком',
    'costs': 'Затраты',
    'quotas': 'Квоты',
    'audit': 'Аудит',
    'access': 'Управление доступом',
    'economics': 'Настройки экономики',
    'economicsSub': 'Настройка тарифов на инференс и стоимости электроэнергии.',
    'tariffCatalog': 'Каталог тарифов',
    'energyEconomics': 'Энергетическая экономика',
    'pricingLogic': 'Логика ценообразования',
    'addUser': 'Добавить пользователя',
    'newTeam': 'Новая команда',
    'newTeamBtn': 'Новая команда',
    'createRole': 'Создать роль',
    'platformRole': 'Роль на платформе',
    'team': 'Команда',
    'allowedModels': 'Разрешенные модели',
    'members': 'Участники',
    'teamRole': 'Роль участников в команде',
    'roleName': 'Название роли',
    'roleDescription': 'Описание роли',
    'permissionsMatrix': 'Матрица прав',
    'currentActivePermissions': 'Сводка активных прав',
    'description': 'Описание',
    'selectModels': 'Выберите модели',
    'autoCalculateCost': 'Авторасчет стоимости',
    'prometheusData': 'Данные Prometheus',
    'wattsPerReplica': 'Ватт на реплику',
    'baseKwhPrice': 'Базовая стоимость (₽/кВт·ч)',
    'currentCluster': 'Текущий кластер',
    'allClusters': 'Все кластеры',
    'modelName': 'Имя модели',
    'replicas': 'Реплики',
    'status': 'Статус',
    'product': 'Продукт',
    'createdAt': 'Создано',
    'actions': 'Действия',
    'active': 'Активен',
    'running': 'Запущено',
    'pending': 'Ожидание',
    'failed': 'Ошибка',
    'succeeded': 'Успешно',
    'rolledBack': 'Откат',
    'multiCluster': 'Мульти-кластер',
    'deployToMultiple': 'Развертывание в нескольких регионах',
    'preDeployValidation': 'Пре-деплой валидация',
    'startDeploy': 'Запустить деплой',
    'startRelease': 'Запустить релиз',
    'releasesSub': 'Отслеживание прогресса, SLO и миграции между кластерами.',
    'route': 'Маршрут',
    'source': 'Источник (Source)',
    'target': 'Цель (Target)',
    'strategy': 'Стратегия',
    'metrics': 'Метрики',
    'timeline': 'Таймлайн',
    'events': 'События',
    'pause': 'Пауза',
    'resume': 'Продолжить',
    'rollback': 'Откатить',
    'skipTo100': 'Сразу 100%',
    'throughput': 'Пропускная способность',
    'latency': 'Задержка',
    'errorRate': 'Ошибки',
    'successRate': 'Успешность',
    'rolling': 'В процессе',
    'paused': 'На паузе',
    'totalCosts': 'Всего затрат',
    'inferenceCost': 'Затраты на инференс',
    'electricityCost': 'Затраты на электроэнергию',
    'totalTokens': 'Всего токенов',
    'energyConsumption': 'Потребление энергии',
    'energyConsumed': 'Потреблено',
    'costsHistory': 'История затрат',
    'ratesManagement': 'Управление тарифами',
    'electricityPrice': 'Цена электричества (за кВт·ч)',
    'inputRate': 'Входящие (1М токенов)',
    'outputRate': 'Исходящие (1М токенов)',
    'groupByModel': 'По моделям',
    'groupByTeam': 'По командам',
    'groupByUser': 'По пользователям',
    'groupByCluster': 'По кластерам',
    'groupByDeployment': 'По деплойментам',
    'inference': 'Инференс',
    'electricity': 'Электричество',
    'combined': 'Комбинированный',
    'stacked': 'Сложенный',
    'dynamics': 'Динамика к прошлому периоду',
    'activeQuotas': 'Активные квоты',
    'warningAlerts': 'Предупреждения',
    'quotasManagement': 'Управление квотами',
    'quotasSub': 'Управление лимитами токенов и затрат по всей платформе.',
    'newQuota': 'Новая квота',
    'subject': 'Субъект',
    'subjectType': 'Тип субъекта',
    'allModels': 'Все модели',
    'limit': 'Лимит',
    'unit': 'Ед. измерения',
    'tokens': 'Токены',
    'requests': 'Запросы',
    'period': 'Период',
    'hour': 'Час',
    'day': 'День',
    'month': 'Месяц',
    'actionOnExceed': 'Действие при превышении',
    'block': 'Блокировать',
    'throttle': 'Троттлить',
    'warn': 'Предупреждать',
    'priority': 'Приоритет',
    'create': 'Создать',
    'cancel': 'Отмена',
    'teamProject': 'Команда / Проект',
    'usageCapacity': 'Использование / Лимит',
    'edit': 'Изменить',
    'healthy': 'Норма',
    'warning': 'С предупреждением',
    'overLimit': 'Лимит превышен',
    'uptime': 'Uptime',
    'costLast24h': 'Затраты (24ч)',
    'metricsOverview': 'Метрики системы',
    'metricsDashboard': 'Метрики',
    'metricsSub': 'Ключевые показатели эффективности и обзор состояния системы.',
    'accessControl': 'Управление доступом',
    'accessSub': 'Управление пользователями, командами и ролями. Доступ определяется членством в командах.',
    'users': 'Пользователи',
    'teams': 'Команды',
    'rolesPermissions': 'Роли и права',
    'manageMembers': 'Управление участниками',
    'userPanel': 'Детали пользователя',
    'teamPanel': 'Детали команды',
    'saveChanges': 'Сохранить изменения',
    'adminSection': 'Администрирование',
    'memberships': 'Членство в командах',
    'addMembership': 'Добавить в команду',
    'name': 'Имя',
    'Email': 'Email',
    'teamName': 'Название команды',
    'infrastructure': 'Инфраструктура',
    'clusters': 'Инфраструктура',
    'nodes': 'Ноды',
    'heartbeat': 'Последний ответ',
    'allocatable': 'Доступно',
    'used': 'Занято',
    'deployable': 'Доступна для деплоя',
    'deployHere': 'Развернуть здесь',
    'gpuUtilization': 'Загрузка GPU',
    'ramUtilization': 'Загрузка RAM',
    'cpuUtilization': 'Загрузка CPU',
    'ready': 'Готова',
    'notReady': 'Не готова',
    'degraded': 'Проблемы',
    'unreachable': 'Недоступен',
    'online': 'В сети',
    'apiTokens': 'Технические токены',
    'deploymentConfig': 'Конфиг деплойментов',
    'avgCostPerToken': 'Ср. цена / Токен',
    'technicalTokens': 'Технические токены',
    'newTechnicalToken': 'Новый технический токен',
    'tokenName': 'Название токена',
    'enterTokenName': 'Введите название токена',
    'deployModelDesc': 'Настройка и развертывание новой LLM в кластеры',
    'configuration': 'Конфигурация',
    'targetCluster': 'Целевой кластер',
    'targetClusterTooltip': 'Физический кластер Kubernetes для развертывания модели.',
    'replicasTooltip': 'Начальное количество экземпляров модели.',
    'modelTooltip': 'Выберите базовую модель для развертывания.',
    'selectClustersReplicas': 'Выберите кластеры и реплики',
    'allocateReplicasTooltip': 'Распределите реплики по нескольким кластерам для высокой доступности.',
    'preDeployValidationTooltip': 'Запуск нагрузочного тестирования до перенаправления трафика. Деплой будет заблокирован при ошибках метрик.',
    'teamTooltip': 'Назначьте развертывание команде для контроля доступа и биллинга.',
    'deployModelBtn': 'Развернуть модель',
    'preDeployPipeline': 'Пайплайн развертывания',
    'creatingPod': 'Создание pod',
    'cluster': 'Кластер',
    'pullingModel': 'Загрузка модели',
    'downloadingWeights': 'Скачивание весов',
    'modelReady': 'Модель готова',
    'servingTraffic': 'Обработка трафика',
    'allocating': 'Выделение...',
    'modelReadyServing': 'Модель готова и обрабатывает запросы',
    'youCanNowSendAPI': 'Теперь можно отправлять API-запросы к кластеру.',
    'deploymentFailed': 'Ошибка развертывания',
    'unknownErrorOccurred': 'Произошла неизвестная ошибка',
    'trafficDesc': 'Настройка глобальной маршрутизации ingress и распределения трафика между кластерами.',
    'newRoute': 'Новый маршрут',
    'activeRoutes': 'Активные маршруты',
    'routingRules': 'Правила маршрутизации',
    'domain': 'Домен',
    'testRequest': 'Тестовый запрос',
    'trafficSplits': 'Сплит трафика',
    'backendsWeights': 'Бэкенды и Веса',
    'deployment': 'Развертывание',
    'addCrossClusterBackend': 'Добавить кросс-кластерный бэкенд',
    'testRequestTrace': 'След тестового запроса',
    'servedBy': 'Обслужено',
    'selectRouteConfig': 'Выберите маршрут для настройки трафика',
    'createNewRoute': 'Создать маршрут',
    'routeName': 'Имя маршрута',
    'domainPath': 'Домен / Путь',
    'backendsConfiguredAfter': 'Бэкенды настраиваются после создания маршрута.',
    'deploymentsDesc': 'Управление и мониторинг активных моделей',
    'loadingDeployments': 'Загрузка...',
    'noDeployments': 'Нет развертываний в этом кластере',
    'release': 'Релиз',
    'rolloutProgress': 'Прогресс выкладки',
    'sloHealth': 'Здоровье / SLO',
    'started': 'Начато',
    'deploymentDetails': 'Детали развертывания',
    'manageNode': 'Управление узлами',
    'autoscalingPolicy': 'Политика авто-масштабирования',
    'tokenGenerated': 'API Токен создан',
    'saveSecurely': 'Надежно сохраните его',
    'currentScalingState': 'Текущее состояние масштабирования',
    'currentReplicas': 'Текущие реплики',
    'activeRequests': 'Активные запросы',
    'queueLength': 'Длина очереди',
    'avgTokensSec': 'Ср. токенов/сек',
    'stableMatch': 'Стабильно (соответствует желаемому)',
    'hpaRuleAssessment': 'Оценка правил HPA',
    'activeReplicaPods': 'Активные поды и телеметрия',
    'overallClusterProgress': 'Общий прогресс кластера',
    'podsDeploymentStatus': 'Статус развертывания подов реплик',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('ru');

  const t = (key: string) => {
    return (translations[language] as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
